language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'intel-android-extra-license.+'

jdk:
  - oraclejdk8

env:
  global:
    # Add this
    - MALLOC_ARENA_MAX=2

sudo: required

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -s "768x1280"
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: ./gradlew :app:build



notifications:
  email:
    recipients:
    - urbsimon@gmail.com
    on_failure: always
    on_success: always